### ISSUE TITLE
Vấn đề về thư viện URSA, sign

### ISSUE THREAD

**Issue by 1412281** [nguyenkha/kcoin-blockchain#19]
mình đang bị vướng chỗ cài ursa để tạo chữ ký.
mình cài trên win 10, nên ko biết là có bạn nào cài được ko nhỉ ?
Như hướng dẫn ở đây thì mình đã làm 2 cách đều ko được.
https://www.npmjs.com/package/ursa

`D:\4_HK1\Web\Deadline\kcoin-wallet-server\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm
\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\no
de_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Reflect.apply: argument is not an array or array-like object
gyp ERR! stack    at ensureStackTrace (Unknown script code:234:9)
gyp ERR! stack    at stackGetter (Unknown script code:244:9)
gyp ERR! stack    at Anonymous function (C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\log.js:183:5)
gyp ERR! stack    at Anonymous function (C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\log.js:286:7)
gyp ERR! stack    at Anonymous function (C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:389:9)
gyp ERR! stack    at F (C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:68:9)
gyp ERR! stack    at E (C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:80:22)
gyp ERR! stack    at Anonymous function (C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:89:9)
gyp ERR! stack    at Anonymous function (C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:42:5)
gyp ERR! stack    at Anonymous function (C:\Users\LAMTRAN\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:36:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\NodejsUwp\\Console\\node.exe" "C:\\Users\\LAMTRAN\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gy
p.js" "rebuild"
gyp ERR! cwd D:\UNIVERSITY\4_HK1\Web\Deadline\kcoin-wallet-server\node_modules\ursa
gyp ERR! node -v v7.0.0-pre8
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! cb() never called!
`

**Comment by nguyenkha** [comment]
Do mình không có windows 10 để test, các bạn giúp thử xem:

- Cài Visual Studio
- OpenSSL
- Python 2.7

**Comment by haingod** [comment]
bạn coi mục install trong này [node-gyp](https://github.com/nodejs/node-gyp)
OpenSSL bạn cài bản này

> http://slproweb.com/download/Win64OpenSSL-1_0_2n.exe

**Comment by 1412281** [comment]
thanks bạn, thì ra là do bản SSL mới ko chạy được ~~"
